name: backend ci

on:
  push:
    branches: [main]
    paths:
      - "olymna-backend/**"
  pull_request:
    branches: [main]
    paths:
      - "olymna-backend/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: olymna-backend

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint || true
